Upgrade all packages to latest core-v8-alpha
Particular/NServiceBus.NHibernate pull request #497
Opened 2020-10-15 11:30 UTC by lailabougria

2020-10-16 05:59 UTC, lailabougria commented on src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
> +    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.627" />
```suggestion
    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="[8.0.0-alpha.627, 9.0.0)" />
```

2020-10-16 05:59 UTC, lailabougria commented on src/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests.csproj
> +    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.627" />
```suggestion
    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="[8.0.0-alpha.627, 9.0.0)" />
```

2020-10-16 05:59 UTC, lailabougria commented on src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
> +    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.627" />
```suggestion
    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="[8.0.0-alpha.627, 9.0.0)" />
```

2020-10-16 05:59 UTC, lailabougria commented on src/NServiceBus.NHibernate.PerformanceTests/NServiceBus.NHibernate.PerformanceTests.csproj
> +    <PackageReference Include="NServiceBus" Version="8.0.0-alpha.627" />
```suggestion
    <PackageReference Include="NServiceBus" Version="[8.0.0-alpha.627, 9.0.0)" />
```

2020-10-16 05:59 UTC, lailabougria commented on src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
> +    <PackageReference Include="NServiceBus" Version="8.0.0-alpha.627" />
```suggestion
    <PackageReference Include="NServiceBus" Version="[8.0.0-alpha.627, 9.0.0)" />
```

2020-10-16 05:59 UTC, lailabougria commented on src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
> +    <PackageReference Include="NServiceBus" Version="8.0.0-alpha.627" />
```suggestion
    <PackageReference Include="NServiceBus" Version="[8.0.0-alpha.627, 9.0.0)" />
```

2020-10-16 06:58 UTC, lailabougria commented on src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
> +    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="[8.0.0-alpha.627, 9.0.0)" />
```suggestion
    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.627" />
```

2020-10-16 06:58 UTC, lailabougria commented on src/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests.csproj
> +    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="[8.0.0-alpha.627, 9.0.0)" />
```suggestion
    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.627" />
```

2020-10-16 06:58 UTC, lailabougria commented on src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
> +    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="[8.0.0-alpha.627, 9.0.0)" />
```suggestion
    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.627" />
```

2020-10-16 06:58 UTC, lailabougria commented on src/NServiceBus.NHibernate.PerformanceTests/NServiceBus.NHibernate.PerformanceTests.csproj
> +    <PackageReference Include="NServiceBus" Version="[8.0.0-alpha.627, 9.0.0)" />
```suggestion
    <PackageReference Include="NServiceBus" Version="8.0.0-alpha.627" />
```

2020-10-16 06:58 UTC, lailabougria commented on src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
> +    <PackageReference Include="NServiceBus" Version="[8.0.0-alpha.627, 9.0.0)" />
```suggestion
    <PackageReference Include="NServiceBus" Version="8.0.0-alpha.627" />
```

2020-10-18 18:11 UTC, lailabougria commented on src/NServiceBus.NHibernate.AcceptanceTests-Oracle/NServiceBus.NHibernate.AcceptanceTests-Oracle.csproj
> +    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.627" />
```suggestion
    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.630" />
```

2020-10-18 18:11 UTC, lailabougria commented on src/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests/NServiceBus.NHibernate.AcceptanceTests-SqlTransportTests.csproj
> +    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.627" />
```suggestion
    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.630" />
```

2020-10-18 18:11 UTC, lailabougria commented on src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj
> +    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.627" />
```suggestion
    <PackageReference Include="NServiceBus.AcceptanceTests.Sources" Version="8.0.0-alpha.630" />
```

2020-10-18 18:11 UTC, lailabougria commented on src/NServiceBus.NHibernate.PerformanceTests/NServiceBus.NHibernate.PerformanceTests.csproj
> +    <PackageReference Include="NServiceBus" Version="8.0.0-alpha.627" />
```suggestion
    <PackageReference Include="NServiceBus" Version="8.0.0-alpha.630" />
```

2020-10-18 18:11 UTC, lailabougria commented on src/NServiceBus.NHibernate.Tests/NServiceBus.NHibernate.Tests.csproj
> +    <PackageReference Include="NServiceBus" Version="8.0.0-alpha.627" />
```suggestion
    <PackageReference Include="NServiceBus" Version="8.0.0-alpha.630" />
```

2020-10-18 18:11 UTC, lailabougria commented on src/NServiceBus.NHibernate/NServiceBus.NHibernate.csproj
> +    <PackageReference Include="NServiceBus" Version="[8.0.0-alpha.627, 9.0.0)" />
```suggestion
    <PackageReference Include="NServiceBus" Version="[8.0.0-alpha.630, 9.0.0)" />
```

2020-10-20 11:48 UTC, ramonsmits requested changes

2020-10-20 11:48 UTC, ramonsmits commented on src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs
> +                    Time = timeout.Time.DateTime,
```suggestion
                    Time = timeout.Time.UtcDateTime,
```

2020-10-20 15:27 UTC, ramonsmits approved these changes

2020-10-20 15:27 UTC, merged